const products = [
  {
    _id: '1',
    name: 'Fruit Cake',
    image: '/images/fruit.jpeg',
    description: 'Fruit Cake',
    brand: 'MERN Cake Shop',
    category: 'Cakes',
    price: 26,
    countInStock: 4,
    rating: 4.7,
    numReviews: 14,
  },
  {
    _id: '2',
    name: 'Coconut Cake',
    image: '/images/coconut.jpeg',
    description: 'Coconut Cake',
    brand: 'MERN Cake Shop',
    category: 'Cakes',
    price: 18,
    countInStock: 5,
    rating: 4.6,
    numReviews: 21,
  },
  {
    _id: '3',
    name: 'Currant Cake',
    image: '/images/currant.jpeg',
    description: 'Currant Cake',
    brand: 'MERN Cake Shop',
    category: 'Cakes',
    price: 24,
    countInStock: 5,
    rating: 4.7,
    numReviews: 11,
  },
  {
    _id: '4',
    name: 'Strawberry Cake',
    image: '/images/strawberry.jpeg',
    description: 'Strawberry Cake',
    brand: 'MERN Cake Shop',
    category: 'Cakes',
    price: 32,
    countInStock: 4,
    rating: 4.8,
    numReviews: 14,
  },
  {
    _id: '5',
    name: 'Blueberry Cake',
    image: '/images/blueberry.jpeg',
    description: 'Blueberry Cake',
    brand: 'MERN Cake Shop',
    category: 'Cakes',
    price: 27,
    countInStock: 2,
    rating: 4.6,
    numReviews: 16,
  },
  {
    _id: '6',
    name: 'Cherry Cake',
    image: '/images/cherry.jpeg',
    description: 'Cherry Cake',
    brand: 'MERN Cake Shop',
    category: 'Cakes',
    price: 38,
    countInStock: 2,
    rating: 4.9,
    numReviews: 8,
  },
]

export default products
